In [1]:
import pandas as pd
import numpy as np


In [2]:
from sklearn.datasets import load_iris
df = load_iris()
X=df.data
y=df.target


In [3]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [4]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y, test_size= 0.2 , random_state=0)

In [6]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [7]:
X_train

array([[ 0.61303014,  0.10850105,  0.94751783,  0.736072  ],
       [-0.56776627, -0.12400121,  0.38491447,  0.34752959],
       [-0.80392556,  1.03851009, -1.30289562, -1.33615415],
       [ 0.25879121, -0.12400121,  0.60995581,  0.736072  ],
       [ 0.61303014, -0.58900572,  1.00377816,  1.25412853],
       [-0.80392556, -0.82150798,  0.04735245,  0.21801546],
       [-0.21352735,  1.73601687, -1.19037495, -1.20664002],
       [ 0.14071157, -0.82150798,  0.72247648,  0.47704373],
       [ 0.02263193, -0.12400121,  0.21613346,  0.34752959],
       [-0.09544771, -1.05401024,  0.10361279, -0.04101281],
       [ 1.0853487 , -0.12400121,  0.94751783,  1.1246144 ],
       [-1.39432376,  0.34100331, -1.41541629, -1.33615415],
       [ 1.20342834,  0.10850105,  0.72247648,  1.38364267],
       [-1.04008484,  1.03851009, -1.24663528, -0.81809761],
       [-0.56776627,  1.50351461, -1.30289562, -1.33615415],
       [-1.04008484, -2.4490238 , -0.1776889 , -0.30004108],
       [ 0.73110978, -0.

In [8]:
X_test

array([[-0.09544771, -0.58900572,  0.72247648,  1.5131568 ],
       [ 0.14071157, -1.98401928,  0.10361279, -0.30004108],
       [-0.44968663,  2.66602591, -1.35915595, -1.33615415],
       [ 1.6757469 , -0.35650346,  1.39760052,  0.736072  ],
       [-1.04008484,  0.80600783, -1.30289562, -1.33615415],
       [ 0.49495049,  0.57350557,  1.22881951,  1.64267094],
       [-1.04008484,  1.03851009, -1.41541629, -1.20664002],
       [ 0.96726906,  0.10850105,  0.49743514,  0.34752959],
       [ 1.0853487 , -0.58900572,  0.55369548,  0.21801546],
       [ 0.25879121, -0.58900572,  0.10361279,  0.08850133],
       [ 0.25879121, -1.05401024,  1.00377816,  0.21801546],
       [ 0.61303014,  0.34100331,  0.38491447,  0.34752959],
       [ 0.25879121, -0.58900572,  0.49743514, -0.04101281],
       [ 0.73110978, -0.58900572,  0.4411748 ,  0.34752959],
       [ 0.25879121, -0.35650346,  0.49743514,  0.21801546],
       [-1.15816448,  1.27101235, -1.35915595, -1.46566829],
       [ 0.14071157, -0.

In [9]:
from sklearn.preprocessing import LabelEncoder
en = LabelEncoder()
y_train = en.fit_transform(y_train)
y_test = en.transform(y_test)

In [10]:
y_train

array([2, 1, 0, 2, 2, 1, 0, 1, 1, 1, 2, 0, 2, 0, 0, 1, 2, 2, 2, 2, 1, 2,
       1, 1, 2, 2, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0,
       1, 0, 2, 1, 0, 1, 2, 1, 0, 2, 2, 2, 2, 0, 0, 2, 2, 0, 2, 0, 2, 2,
       0, 0, 2, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 1, 0, 0, 1, 0, 2, 1, 2, 1,
       0, 2, 0, 2, 0, 0, 2, 0, 2, 1, 1, 1, 2, 2, 1, 1, 0, 1, 2, 2, 0, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 2, 0], dtype=int64)

In [11]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [12]:
from sklearn.naive_bayes import GaussianNB
nb =GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [13]:
y_pred = nb.predict(X_test)

In [14]:
y_pred


array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [15]:
y_test

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(y_test , y_pred)
acc

0.9666666666666667

In [17]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0], dtype=int64)